// 
var num7 = 5;
var num8 = 4;
console.log(num7 + num8);
var num9 = 10;
var num10 = 6;
var sum = num9 + num10;
console.log(sum);
var num11 = 10;
var num12 = 2;
var sub = num11 - num12;
console.log(sub);
var num1 = 10;
var num2 = 2;
var mul = num1 * num2;
console.log(mul);
var num3 = 21;
var num4 = 5;
var mod = num3 % num4;
console.log(mod);
var num5 = 5;
var num6 = 2;
var power = Math.pow(num5, num6);
console.log(power);
var firstname = "tabiq";
var lastname = "chohan";
console.log(firstname + " " + lastname);
var n = 5;
n = n + 5;
console.log(n);
console.log(10 == 10);
console.log(10 === 10);
console.log(10 != 5);
console.log(5 > 2);
console.log(5 < 2);
console.log(5 <= 5);
